# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-05 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analysed_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_model', models.FileField(blank=True, default='not applicable', null=True, upload_to='file/')),
            ],
        ),
    ]
